name: Gitfolio-Generate
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          repository: ${{ github.repository}}
          ref: main

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: 16.x 

      - name: Install dependencies
        run: |
          npm i gitfolio -g
          gitfolio build ${{ github.repository_owner }} --theme dark --sort star

  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        repository: ${{ github.repository}}
        ref: gh-pages
